### ISSUE TITLE
Add caching of oauth token and possibly other information between invocations

### ISSUE THREAD

**Issue by sconklin** [phase4ground/flexclient#2]
Currently, the user must authenticate with the FlexLink site for every connection. It's possible to cache tokens and avoid this step.
Add support for doing that.

**Comment by dkozel** [comment]
1) add `offline_access` to the initial login request's `scope`
2) cache the `refresh_token` and expiry time from the successful response
3) on each launch check for a saved `refresh_token` stored somewhere (as a file in some OS supported application settings directory?)
4) use the `refresh_token` to obtain a new `id_token` and `refresh_token`

Needs to handle detecting an out of date `refresh_token` and relaunching the auth process. I've tested obtaining the refresh_token and obtaining a new id_token. I'll file a PR with an updated utility for manually managing tokens.

https://auth0.com/docs/secure/tokens/refresh-tokens/get-refresh-tokens
https://auth0.com/docs/secure/tokens/refresh-tokens/use-refresh-tokens

**Comment by dkozel** [comment]
I've implemented the following in a standalone utility available at [dkozel/flexclient - SmartLink Update](https://github.com/dkozel/flexclient/blob/790956bd58f7526b037144ddaf847ccf8de68168/utils/SmartLinkAuthClient.py)

The DigiKey API library was a very useful reference for the OAuth2 flow.
https://github.com/peeter123/digikey-api/blob/9928043068e541d21ad8786ddd9687f7801ad7a9/digikey/oauth/oauth2.py#L57

- Refactored the existing login to be substantially more robust and user-friendly.
- Added storing/loading the access token to a file.
- Added checking of the token's expiration.
- Added using the refresh token flow to renew the access token when needed.

Next step is to do a little more tidying of the code in this auth class and integrate it into the main library.

**Comment by mas-dse-dhpancha** [comment]
So is the SmartLinkAuthClient.py file intended to be used if you have the local IP address of the flexradio or do we still need to log in through the flexlink site for authentication?

**Comment by dkozel** [comment]
@mas-dse-dhpancha I've never had local access to a Flex so have always used the FlexLink access. The method of detecting and connecting to a local radio is much simpler but needs someone with local access to spend a few hours writing it and testing it out.

**Comment by sconklin** [comment]
It's been over a year, but IIRC I did add the ability to connect locally without using FlexLink. The intent of this issue was for caching only in the FlexLink case.

I don't remember whether any of the code in SmartLinkAuthClient.py is called in the local LAN case. 

I don't currently have a radio on the LAN so I can't test or experiment.

**Comment by mas-dse-dhpancha** [comment]
dkozel, thanks. Were you able to connect to a Flexradio 6600 using the radio serial number inputted in the Main.py file and test files using flexclient package provided on Github? Are there only specific serial numbers allocated to use the flexclient? I seem to be having issues doing that:
Traceback (most recent call last):
  File "Main.py", line 20, in <module>
    radioInfo = smartlink.GetRadioFromAvailable(SERIAL)
  File "/home/niwc/Downloads/flexclient-main/src/flexclient/SmartLink.py", line 230, in GetRadioFromAvailable
    raise ValueError("Requested serial number not in authorized list")
ValueError: Requested serial number not in authorized list
